name: release_manager

on: 
  pull_request:
    types:
      - opened

jobs:
  processing_release_manager:
    name: collecting_release_version
    runs-on: [ self-hosted, linux, release_manager ]
    steps:
    - id: step1
      name: Identify the newly added file 
      run: |
        echo "Repo name is ${{ github.repository }} and the PR number is ${{ github.event.pull_request.number }}"
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -H "Authorization: Bearer $(cat ~/.gh_secrets)" -G $URL | jq -r '.[] | .filename')
        echo ${FILES}
