name: release_manager

on: push

jobs:
  processing_release_manager:
    name: collecting_release_version
    runs-on: [ self-hosted, linux, release_manager ]
    steps:
    - id: step1
      name: Identify the newly added file 
      run: |
        echo "This is testing GitHub Workflow"
