name: release_manager

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: number

jobs:
  processing_release_manager:
    name: collecting_release_version
    runs-on: [ self-hosted, linux, release_manager ]
    run: |
      echo "This is testing GitHub Workflow"
